name: Benchmark
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.yaml'
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.20"
          cache: true

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: setup aho-corasick for cgo
        run: |
          rustup toolchain install stable
          rustup default stable
          cargo build --release
        working-directory: buildtools/aho-corasick

      - run: go run mage.go benchall
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/buildtools/aho-corasick/target/release

      - run: go run mage.go wafbenchall
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/buildtools/aho-corasick/target/release

      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: build/*bench*.txt
